### PR TITLE
Changed date to the actual release date of the post.  Added name and description fields to dependency files

### PR DESCRIPTION
**Pull request by KetsuN**
@useffc or @joshfinnie Would one of you mind taking a look at this?  I've had a few comments on the post so far with these being incorrect.

### CODE REVIEW

**Comment by useffc** [comment]
@KetsuN lgtm, merging

**Comment by Jwpe** [comment]
Hype

**Comment by joshfinnie** [comment]
Has this been deployed @useffc ?

**Comment by useffc** [comment]
@joshfinnie deployed. thanks for the reminder.

**Pull request merged**
