### PR TITLE
DRF Getting Started - Part 3

### PR DESCRIPTION
**Pull request by KetsuN**

### CODE REVIEW

**Comment by KetsuN** [comment]
@joshfinnie Mind taking a look?

**Comment by joshfinnie** [comment]
At this rate, I am scared to publish this without part 4 already written ;-)

**Comment by joshfinnie** [comment]
Looks mighty fine @KetsuN. Any preference on when we release this? I can do it tomorrow morning...

**Comment by KetsuN** [comment]
Tomorrow morning works for me!

**Pull request merged**
