### PR TITLE
Getting Started with Django Rest Framework and AngularJS - Part 2

### PR DESCRIPTION
**Pull request by KetsuN**
Stemmed from #4 
Topics: Model creation and queries through the shell.

Code section can be found [here](https://github.com/TrackMaven/getting-started-with-drf-angular/tree/part-2) and should be part of the QA for this part.

### CODE REVIEW

**Comment by KetsuN** [comment]
@joshfinnie I think this is ready for review!  You may want to double-check the `part-2` branch of the code repo as well.

**Comment by KetsuN** [comment]
@joshfinnie I cleaned up the portion you mentioned and a few lines afterwards that needed some clarity as well.  Let me know if there is anything else to make more clear!

**Comment by joshfinnie** [comment]
Nice, wanna rebase @KetsuN?

**Comment by KetsuN** [comment]
@joshfinnie Rebased!

**Pull request merged**
